name       : haskell-xml-conduit
version    : 1.6.0
release    : 2
source     :
    - https://hackage.haskell.org/package/xml-conduit-1.6.0/xml-conduit-1.6.0.tar.gz : 24a46d41c8aac21acb41f1d79ec01947bbe7ab98f737eb15775d2294e2c14c10
license    : MIT
component  : programming.haskell
summary    : This package provides parsing and rendering functions for XML.
description: |
    This package provides parsing and rendering functions for XML.
builddeps  :
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-data-default-class
    - haskell-xml-types
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
