name       : haskell-xml-conduit
version    : 1.8.0
release    : 3
source     :
    - http://hackage.haskell.org/package/xml-conduit-1.8.0/xml-conduit-1.8.0.tar.gz : 0382bfd3627be4970b11228948274faef51ca9a2590a7723b5787a7205a52036
license    : MIT
component  : programming.haskell
summary    : This package provides parsing and rendering functions for XML.
description: |
    This package provides parsing and rendering functions for XML.
builddeps  :
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-data-default-class
    - haskell-monad-control
    - haskell-xml-types
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
