name       : haskell-xml-conduit
version    : 1.7.0
release    : 1
source     :
    - https://hackage.haskell.org/package/xml-conduit-1.7.0/xml-conduit-1.7.0.tar.gz : e644117217ad2efee0a5e4ea488490ddac7de5dba6813212e0031b2b0a340a3c
license    : MIT
component  : programming.haskell
summary    : This package provides parsing and rendering functions for XML.
description: |
    This package provides parsing and rendering functions for XML.
builddeps  :
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-conduit-extra
    - haskell-data-default-class
    - haskell-xml-types
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
