name       : haskell-xml-conduit
version    : 1.8.0.1
release    : 4
source     :
    - https://hackage.haskell.org/package/xml-conduit-1.8.0.1/xml-conduit-1.8.0.1.tar.gz : 980b2f13ab8f54d8c2cbf92d186d5fac6c6ead42197c6687bd81e2fea2afef9c
license    : MIT
component  : programming.haskell
summary    : This package provides parsing and rendering functions for XML.
description: |
    This package provides parsing and rendering functions for XML.
builddeps  :
    - haskell-blaze-html-devel
    - haskell-cabal-install
    - haskell-conduit-extra-devel
    - haskell-data-default-class-devel
    - haskell-xml-types-devel
rundeps    :
    - devel:
        - haskell-blaze-html-devel
        - haskell-conduit-extra-devel
        - haskell-data-default-class-devel
        - haskell-xml-types-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
